services:
  web:
    build: .
    restart: always
    ports:
      - "3700:8000"
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SITE_URL=${SITE_URL}
    command: sh /app/entrypoint.sh

volumes:
  static_data:
  media_data:
