databases:
  - name: citizen-db
    plan: free
    databaseName: citizen
    user: citizen

services:
  - type: web
    name: citizen
    runtime: docker
    plan: free
    branch: prod
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: SITE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: citizen-db
          property: connectionString
