services:
  - type: web
    name: citizen
    runtime: docker
    plan: free
    branch: nodatabase
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: SITE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
