# Generated by Django 5.1.7 on 2026-04-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='페이지뷰')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='순방문자')),
            ],
            options={
                'verbose_name': '접속 통계',
                'verbose_name_plural': '접속 통계',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('path', models.CharField(max_length=500, verbose_name='경로')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('referer', models.TextField(blank=True, default='', verbose_name='Referer')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='방문일시')),
            ],
            options={
                'verbose_name': '방문 로그',
                'verbose_name_plural': '방문 로그',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='admin_memo',
            field=models.TextField(blank=True, default='', verbose_name='관리자 메모'),
        ),
    ]
