# Generated by Django 5.1.7 on 2026-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sitevisit_visitorlog_consultation_admin_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('개인회생', '개인회생'), ('개인파산', '개인파산'), ('민사', '민사'), ('형사', '형사'), ('가사/이혼', '가사/이혼'), ('법인회생', '법인회생'), ('일반', '일반')], default='일반', max_length=20, verbose_name='분류')),
                ('question', models.CharField(max_length=300, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '자주하는 질문',
                'verbose_name_plural': '자주하는 질문',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
