# Generated by Django 5.1.7 on 2026-04-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnosis_data',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='자가진단 답변'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='source',
            field=models.CharField(choices=[('일반', '일반 상담'), ('자가진단', '자가진단'), ('랜딩페이지', '랜딩페이지')], default='일반', max_length=20, verbose_name='유입 경로'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='연락처'),
        ),
    ]
